title: Alexandre Martin
description: >- # this means to ignore newlines until "baseurl:"
  Alex's website.
github_username: scalexm
linkedin_username: alexandre-g-martin
linkedin_username_display: Alexandre Martin

# Build settings
markdown: kramdown
theme: minima

header_pages:
  - posts.md
